-- -----------------------------------------------------------------
-- Nombre 	: init.sql
-- Autor	: Grupo 502
-- Fecha	: Mayo 2016
-- Desc		: Script de carga inicial
-- -----------------------------------------------------------------
USE central_dev;

-- PARAMETRIZACION BASICA
INSERT INTO param (keyParam , valueParam, keyText, valueText, creationDate) VALUES ('baseUrl', 'localhost/iparkweb', 'Dominio', 'URL Base de la Plataforma', now());
INSERT INTO param (keyParam , valueParam, keyText, valueText, creationDate) VALUES ('contact','contacto@iparking.com.ar','Direccion de Contacto', 'Direccion de Contacto para cientes', now());
INSERT INTO param (keyParam , valueParam, keyText, valueText, creationDate) VALUES ('mail','cesarcappetto@sw-ingenieria.com.ar','Direccion de Origen (email)', '',now());
INSERT INTO param (keyParam , valueParam, keyText, valueText, creationDate) VALUES ('sender','iParking','Nombre de Origen (email)','', now());
INSERT INTO param (keyParam , valueParam, keyText, valueText, creationDate) VALUES ('smtp','smtp.sw-ingenieria.com.ar','Nombre (smtp)', '', now());
INSERT INTO param (keyParam , valueParam, keyText, valueText, creationDate) VALUES ('port','2525','Puerto (smtp)','', now());
INSERT INTO param (keyParam , valueParam, keyText, valueText, creationDate) VALUES ('user','cesarcappetto@sw-ingenieria.com.ar','Usuario (smtp)', '', now());
INSERT INTO param (keyParam , valueParam, keyText, valueText, creationDate) VALUES ('password','1234','Password (smtp)', '', now());
INSERT INTO param (keyParam , valueParam, keyText, valueText, creationDate) VALUES ('security','','Tipo de Seguridad (smtp)','', now());

-- PAISES
INSERT INTO country(description) VALUES ('No disponible');
INSERT INTO country(description) VALUES ('Argentina');

-- PROVINCIAS
INSERT INTO province(description,country_id) VALUES ('No Disponible', 1);
INSERT INTO province(description,country_id) VALUES ('Capital Federal',2);
INSERT INTO province(description,country_id) VALUES ('GBA Norte',2);
INSERT INTO province(description,country_id) VALUES ('GBA Sur',2);
INSERT INTO province(description,country_id) VALUES ('GBA Oeste',2);
INSERT INTO province(description,country_id) VALUES ('Buenos Aires',2);

-- PARTIDOS
INSERT INTO state(description,province_id) VALUES ('No Disponible', 1 );
INSERT INTO state(description,province_id) VALUES ('Capital Federal', 2 );
INSERT INTO state(description,province_id) VALUES ('General San Martin', 3 );
INSERT INTO state(description,province_id) VALUES ('José C. Paz', 3 );
INSERT INTO state(description,province_id) VALUES ('Malvinas Argentinas', 3 );
INSERT INTO state(description,province_id) VALUES ('San Fernando', 3 );
INSERT INTO state(description,province_id) VALUES ('San Isidro', 3 );
INSERT INTO state(description,province_id) VALUES ('San Miguel', 3 );
INSERT INTO state(description,province_id) VALUES ('Tigre', 3 );
INSERT INTO state(description,province_id) VALUES ('Vicente Lopez', 3 );
INSERT INTO state(description,province_id) VALUES ('Almirante Brown', 4 );
INSERT INTO state(description,province_id) VALUES ('Avellaneda', 4 );
INSERT INTO state(description,province_id) VALUES ('Berazategui', 4 );
INSERT INTO state(description,province_id) VALUES ('Esteban Echeverría', 4 );
INSERT INTO state(description,province_id) VALUES ('Florencio Varela', 4 );
INSERT INTO state(description,province_id) VALUES ('Lanús', 4 );
INSERT INTO state(description,province_id) VALUES ('Lomas de Zamora', 4 );
INSERT INTO state(description,province_id) VALUES ('Quilmes', 4 );
INSERT INTO state(description,province_id) VALUES ('Hurlingham', 5 );
INSERT INTO state(description,province_id) VALUES ('Ituzaingó', 5 );
INSERT INTO state(description,province_id) VALUES ('La Matanza', 5 );
INSERT INTO state(description,province_id) VALUES ('Merlo', 5 );
INSERT INTO state(description,province_id) VALUES ('Moreno', 5 );
INSERT INTO state(description,province_id) VALUES ('Morón', 5 );
INSERT INTO state(description,province_id) VALUES ('Tres de Febrero', 5 );
INSERT INTO state(description,province_id) VALUES ('A. gonzalez chavez', 6 );
INSERT INTO state(description,province_id) VALUES ('Adolfo alsina', 6 );
INSERT INTO state(description,province_id) VALUES ('Alberti', 6 );
INSERT INTO state(description,province_id) VALUES ('Arrecifes', 6 );
INSERT INTO state(description,province_id) VALUES ('Ayacucho', 6 );
INSERT INTO state(description,province_id) VALUES ('Azul', 6 );
INSERT INTO state(description,province_id) VALUES ('Bahia blanca', 6 );
INSERT INTO state(description,province_id) VALUES ('Balcarce', 6 );
INSERT INTO state(description,province_id) VALUES ('Baradero', 6 );
INSERT INTO state(description,province_id) VALUES ('Benito juarez', 6 );
INSERT INTO state(description,province_id) VALUES ('Berisso', 6 );
INSERT INTO state(description,province_id) VALUES ('Bolivar', 6 );
INSERT INTO state(description,province_id) VALUES ('Bragado', 6 );
INSERT INTO state(description,province_id) VALUES ('Brandsen', 6 );
INSERT INTO state(description,province_id) VALUES ('Campana', 6 );
INSERT INTO state(description,province_id) VALUES ('Cañuelas', 6 );
INSERT INTO state(description,province_id) VALUES ('Capitan sarmiento', 6 );
INSERT INTO state(description,province_id) VALUES ('Carlos casares', 6 );
INSERT INTO state(description,province_id) VALUES ('Carlos tejedor', 6 );
INSERT INTO state(description,province_id) VALUES ('Carmen de areco', 6 );
INSERT INTO state(description,province_id) VALUES ('Castelli', 6 );
INSERT INTO state(description,province_id) VALUES ('Chacabuco', 6 );
INSERT INTO state(description,province_id) VALUES ('Chascomus', 6 );
INSERT INTO state(description,province_id) VALUES ('Chivilcoy', 6 );
INSERT INTO state(description,province_id) VALUES ('Colon', 6 );
INSERT INTO state(description,province_id) VALUES ('Coronel dorrego', 6 );
INSERT INTO state(description,province_id) VALUES ('Coronel pringles', 6 );
INSERT INTO state(description,province_id) VALUES ('Coronel rosales', 6 );
INSERT INTO state(description,province_id) VALUES ('Coronel suarez', 6 );
INSERT INTO state(description,province_id) VALUES ('Daireaux', 6 );
INSERT INTO state(description,province_id) VALUES ('De la costa', 6 );
INSERT INTO state(description,province_id) VALUES ('Dolores', 6 );
INSERT INTO state(description,province_id) VALUES ('Ensenada', 6 );
INSERT INTO state(description,province_id) VALUES ('Escobar', 6 );
INSERT INTO state(description,province_id) VALUES ('Exaltacion de la cruz', 6 );
INSERT INTO state(description,province_id) VALUES ('Ezeiza', 6 );
INSERT INTO state(description,province_id) VALUES ('Florentino ameghino', 6 );
INSERT INTO state(description,province_id) VALUES ('General alvarado', 6 );
INSERT INTO state(description,province_id) VALUES ('General alvear', 6 );
INSERT INTO state(description,province_id) VALUES ('General arenales', 6 );
INSERT INTO state(description,province_id) VALUES ('General belgrano', 6 );
INSERT INTO state(description,province_id) VALUES ('General guido', 6 );
INSERT INTO state(description,province_id) VALUES ('General lamadrid', 6 );
INSERT INTO state(description,province_id) VALUES ('General las heras', 6 );
INSERT INTO state(description,province_id) VALUES ('General lavalle', 6 );
INSERT INTO state(description,province_id) VALUES ('General madariaga', 6 );
INSERT INTO state(description,province_id) VALUES ('General paz', 6 );
INSERT INTO state(description,province_id) VALUES ('General pinto', 6 );
INSERT INTO state(description,province_id) VALUES ('General pueyrredon', 6 );
INSERT INTO state(description,province_id) VALUES ('General rodriguez', 6 );
INSERT INTO state(description,province_id) VALUES ('General viamonte', 6 );
INSERT INTO state(description,province_id) VALUES ('General villegas', 6 );
INSERT INTO state(description,province_id) VALUES ('Guamini', 6 );
INSERT INTO state(description,province_id) VALUES ('Hipolito yrigoyen', 6 );
INSERT INTO state(description,province_id) VALUES ('Junin', 6 );
INSERT INTO state(description,province_id) VALUES ('La plata', 6 );
INSERT INTO state(description,province_id) VALUES ('Laprida', 6 );
INSERT INTO state(description,province_id) VALUES ('Las flores', 6 );
INSERT INTO state(description,province_id) VALUES ('Leandro n. alem', 6 );
INSERT INTO state(description,province_id) VALUES ('Lincoln', 6 );
INSERT INTO state(description,province_id) VALUES ('Loberia', 6 );
INSERT INTO state(description,province_id) VALUES ('Lobos', 6 );
INSERT INTO state(description,province_id) VALUES ('Lujan', 6 );
INSERT INTO state(description,province_id) VALUES ('Magdalena', 6 );
INSERT INTO state(description,province_id) VALUES ('Maipu', 6 );
INSERT INTO state(description,province_id) VALUES ('Mar chiquita', 6 );
INSERT INTO state(description,province_id) VALUES ('Marcos paz', 6 );
INSERT INTO state(description,province_id) VALUES ('Mercedes', 6 );
INSERT INTO state(description,province_id) VALUES ('Monte', 6 );
INSERT INTO state(description,province_id) VALUES ('Monte hermoso', 6 );
INSERT INTO state(description,province_id) VALUES ('Navarro', 6 );
INSERT INTO state(description,province_id) VALUES ('Necochea', 6 );
INSERT INTO state(description,province_id) VALUES ('Nueve de julio', 6 );
INSERT INTO state(description,province_id) VALUES ('Olavarria', 6 );
INSERT INTO state(description,province_id) VALUES ('Patagones', 6 );
INSERT INTO state(description,province_id) VALUES ('Pehuajo', 6 );
INSERT INTO state(description,province_id) VALUES ('Pellegrini', 6 );
INSERT INTO state(description,province_id) VALUES ('Pergamino', 6 );
INSERT INTO state(description,province_id) VALUES ('Pila', 6 );
INSERT INTO state(description,province_id) VALUES ('Pilar', 6 );
INSERT INTO state(description,province_id) VALUES ('Pinamar', 6 );
INSERT INTO state(description,province_id) VALUES ('Presidente peron', 6 );
INSERT INTO state(description,province_id) VALUES ('Puan', 6 );
INSERT INTO state(description,province_id) VALUES ('Punta indio', 6 );
INSERT INTO state(description,province_id) VALUES ('Ramallo', 6 );
INSERT INTO state(description,province_id) VALUES ('Rauch', 6 );
INSERT INTO state(description,province_id) VALUES ('Rivadavia', 6 );
INSERT INTO state(description,province_id) VALUES ('Rojas', 6 );
INSERT INTO state(description,province_id) VALUES ('Roque perez', 6 );
INSERT INTO state(description,province_id) VALUES ('Saavedra', 6 );
INSERT INTO state(description,province_id) VALUES ('Saladillo', 6 );
INSERT INTO state(description,province_id) VALUES ('Salliquelo', 6 );
INSERT INTO state(description,province_id) VALUES ('Salto', 6 );
INSERT INTO state(description,province_id) VALUES ('San andres de giles', 6 );
INSERT INTO state(description,province_id) VALUES ('San antonio de areco', 6 );
INSERT INTO state(description,province_id) VALUES ('San cayetano', 6 );
INSERT INTO state(description,province_id) VALUES ('San nicolas', 6 );
INSERT INTO state(description,province_id) VALUES ('San pedro', 6 );
INSERT INTO state(description,province_id) VALUES ('San vicente', 6 );
INSERT INTO state(description,province_id) VALUES ('Suipacha', 6 );
INSERT INTO state(description,province_id) VALUES ('Tandil', 6 );
INSERT INTO state(description,province_id) VALUES ('Tapalque', 6 );
INSERT INTO state(description,province_id) VALUES ('Tordillo', 6 );
INSERT INTO state(description,province_id) VALUES ('Tornquist', 6 );
INSERT INTO state(description,province_id) VALUES ('Trenque lauquen', 6 );
INSERT INTO state(description,province_id) VALUES ('Tres arroyos', 6 );
INSERT INTO state(description,province_id) VALUES ('Tres lomas', 6 );
INSERT INTO state(description,province_id) VALUES ('Veinticinco de mayo', 6 );
INSERT INTO state(description,province_id) VALUES ('Villa gesell', 6 );
INSERT INTO state(description,province_id) VALUES ('Villarino', 6 );
INSERT INTO state(description,province_id) VALUES ('Zarate', 6 );

-- LOCALIDADES
INSERT INTO city(description,state_id) VALUES ('No Disponible', 1 );
INSERT INTO city(description,state_id) VALUES ('Adrogué', 11 );
INSERT INTO city(description,state_id) VALUES ('Burzaco', 11 );
INSERT INTO city(description,state_id) VALUES ('Claypole', 11 );
INSERT INTO city(description,state_id) VALUES ('Don orione', 11 );
INSERT INTO city(description,state_id) VALUES ('Glew', 11 );
INSERT INTO city(description,state_id) VALUES ('José mármol ', 11 );
INSERT INTO city(description,state_id) VALUES ('Longchamps', 11 );
INSERT INTO city(description,state_id) VALUES ('Malvinas argentinas ', 11 );
INSERT INTO city(description,state_id) VALUES ('Ministro rivadavia', 11 );
INSERT INTO city(description,state_id) VALUES ('Rafael calzada', 11 );
INSERT INTO city(description,state_id) VALUES ('San francisco solano ', 11 );
INSERT INTO city(description,state_id) VALUES ('San jose', 11 );
INSERT INTO city(description,state_id) VALUES ('Abasto', 2 );
INSERT INTO city(description,state_id) VALUES ('Agronomía', 2 );
INSERT INTO city(description,state_id) VALUES ('Almagro', 2 );
INSERT INTO city(description,state_id) VALUES ('Balvanera', 2 );
INSERT INTO city(description,state_id) VALUES ('Barracas', 2 );
INSERT INTO city(description,state_id) VALUES ('Barrio norte', 2 );
INSERT INTO city(description,state_id) VALUES ('Belgrano', 2 );
INSERT INTO city(description,state_id) VALUES ('Boedo', 2 );
INSERT INTO city(description,state_id) VALUES ('Caballito', 2 );
INSERT INTO city(description,state_id) VALUES ('Chacarita', 2 );
INSERT INTO city(description,state_id) VALUES ('Coghlan', 2 );
INSERT INTO city(description,state_id) VALUES ('Colegiales', 2 );
INSERT INTO city(description,state_id) VALUES ('Constitucion', 2 );
INSERT INTO city(description,state_id) VALUES ('Flores', 2 );
INSERT INTO city(description,state_id) VALUES ('Floresta', 2 );
INSERT INTO city(description,state_id) VALUES ('La boca', 2 );
INSERT INTO city(description,state_id) VALUES ('Liniers', 2 );
INSERT INTO city(description,state_id) VALUES ('Mataderos', 2 );
INSERT INTO city(description,state_id) VALUES ('Micro centro', 2 );
INSERT INTO city(description,state_id) VALUES ('Monserrat', 2 );
INSERT INTO city(description,state_id) VALUES ('Monte castro', 2 );
INSERT INTO city(description,state_id) VALUES ('Nuñez', 2 );
INSERT INTO city(description,state_id) VALUES ('Nueva pompeya', 2 );
INSERT INTO city(description,state_id) VALUES ('Palermo', 2 );
INSERT INTO city(description,state_id) VALUES ('Palermo viejo', 2 );
INSERT INTO city(description,state_id) VALUES ('Parque avellaneda', 2 );
INSERT INTO city(description,state_id) VALUES ('Parque chacabuco', 2 );
INSERT INTO city(description,state_id) VALUES ('Parque patricios', 2 );
INSERT INTO city(description,state_id) VALUES ('Paternal', 2 );
INSERT INTO city(description,state_id) VALUES ('Puerto madero', 2 );
INSERT INTO city(description,state_id) VALUES ('Recoleta', 2 );
INSERT INTO city(description,state_id) VALUES ('Retiro', 2 );
INSERT INTO city(description,state_id) VALUES ('Saavedra', 2 );
INSERT INTO city(description,state_id) VALUES ('San cristobal', 2 );
INSERT INTO city(description,state_id) VALUES ('San nicolas', 2 );
INSERT INTO city(description,state_id) VALUES ('San telmo', 2 );
INSERT INTO city(description,state_id) VALUES ('Velez sarsfield', 2 );
INSERT INTO city(description,state_id) VALUES ('Versalles', 2 );
INSERT INTO city(description,state_id) VALUES ('Villa crespo', 2 );
INSERT INTO city(description,state_id) VALUES ('Villa devoto', 2 );
INSERT INTO city(description,state_id) VALUES ('Villa general mitre', 2 );
INSERT INTO city(description,state_id) VALUES ('Villa lugano', 2 );
INSERT INTO city(description,state_id) VALUES ('Villa luro', 2 );
INSERT INTO city(description,state_id) VALUES ('Villa ortuzar', 2 );
INSERT INTO city(description,state_id) VALUES ('Villa pueyrredon', 2 );
INSERT INTO city(description,state_id) VALUES ('Villa real', 2 );
INSERT INTO city(description,state_id) VALUES ('Villa riachuelo', 2 );
INSERT INTO city(description,state_id) VALUES ('Villa santa rita', 2 );
INSERT INTO city(description,state_id) VALUES ('Villa soldati', 2 );
INSERT INTO city(description,state_id) VALUES ('Villa urquiza', 2 );
INSERT INTO city(description,state_id) VALUES ('Villa del parque', 2 );
INSERT INTO city(description,state_id) VALUES ('Villa Ayacucho', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa Ballester', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa Barrio Para Jefes y Oficiales General San Martín', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa Barrio Parque Figueroa Alcorta', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa Bernardo de Monteagudo', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa Billinghurst', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa Chacabuco', 3 );
INSERT INTO city(description,state_id) VALUES ('Ciudad del Libertador General San Martín', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa Ciudad Jardín el Libertador', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa Coronel José María Zapiola', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa General Antonio José de Sucre', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa General Eugenio Necochea', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa General José Tomás Guido', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa General Juan Gregorio de Las Heras', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa Godoy Cruz', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa Granaderos de San Martín', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa Gregoria Matorras', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa José León Suárez', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa Juan Martín de Pueyrredón', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa Libertad', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa Lynch', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa Maipú', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa María Irene de los Remedios de Escalada', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa Marqués Alejandro María de Aguado', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa Parque San Lorenzo', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa San Andrés', 3 );
INSERT INTO city(description,state_id) VALUES ('Villa Yapeyú', 3 );
INSERT INTO city(description,state_id) VALUES ('Área de Promoción El Triángulo', 5 );
INSERT INTO city(description,state_id) VALUES ('Grand Bourg', 5 );
INSERT INTO city(description,state_id) VALUES ('Ingeniero Adolfo Sourdeaux', 5 );
INSERT INTO city(description,state_id) VALUES ('Ingeniero Pablo Nogués', 5 );
INSERT INTO city(description,state_id) VALUES ('Los Polvorines', 5 );
INSERT INTO city(description,state_id) VALUES ('Malvinas Argentinas ', 5 );
INSERT INTO city(description,state_id) VALUES ('Tortuguitas', 5 );
INSERT INTO city(description,state_id) VALUES ('Villa de Mayo', 5 );
INSERT INTO city(description,state_id) VALUES ('Tierras Altas', 5 );
INSERT INTO city(description,state_id) VALUES ('San Fernando', 6 );
INSERT INTO city(description,state_id) VALUES ('Victoria', 6 );
INSERT INTO city(description,state_id) VALUES ('Virreyes', 6 );
INSERT INTO city(description,state_id) VALUES ('Islas', 6 );
INSERT INTO city(description,state_id) VALUES ('Villa Adelina', 7 );
INSERT INTO city(description,state_id) VALUES ('Boulogne', 7 );
INSERT INTO city(description,state_id) VALUES ('Martínez', 7 );
INSERT INTO city(description,state_id) VALUES ('Acassuso', 7 );
INSERT INTO city(description,state_id) VALUES ('San Isidro', 7 );
INSERT INTO city(description,state_id) VALUES ('Béccar', 7 );
INSERT INTO city(description,state_id) VALUES ('Bella Vista', 8 );
INSERT INTO city(description,state_id) VALUES ('Muñiz', 8 );
INSERT INTO city(description,state_id) VALUES ('San Miguel', 8 );
INSERT INTO city(description,state_id) VALUES ('Santa María', 8 );
INSERT INTO city(description,state_id) VALUES ('Tigre', 9 );
INSERT INTO city(description,state_id) VALUES ('Don Torcuato', 9 );
INSERT INTO city(description,state_id) VALUES ('General Pacheco', 9 );
INSERT INTO city(description,state_id) VALUES ('El Talar', 9 );
INSERT INTO city(description,state_id) VALUES ('Benavídez', 9 );
INSERT INTO city(description,state_id) VALUES ('Dique Luján', 9 );
INSERT INTO city(description,state_id) VALUES ('Nordelta', 9 );
INSERT INTO city(description,state_id) VALUES ('Ricardo Rojas', 9 );
INSERT INTO city(description,state_id) VALUES ('Rincón de Milberg', 9 );
INSERT INTO city(description,state_id) VALUES ('Troncos del Talar', 9 );
INSERT INTO city(description,state_id) VALUES ('Delta de Tigre', 9 );
INSERT INTO city(description,state_id) VALUES ('Carapachay', 10 );
INSERT INTO city(description,state_id) VALUES ('Florida', 10 );
INSERT INTO city(description,state_id) VALUES ('Florida Oeste', 10 );
INSERT INTO city(description,state_id) VALUES ('La Lucila', 10 );
INSERT INTO city(description,state_id) VALUES ('Munro', 10 );
INSERT INTO city(description,state_id) VALUES ('Olivos', 10 );
INSERT INTO city(description,state_id) VALUES ('Vicente López', 10 );
INSERT INTO city(description,state_id) VALUES ('Villa Adelina', 10 );
INSERT INTO city(description,state_id) VALUES ('Villa Martelli', 10 );
INSERT INTO city(description,state_id) VALUES ('José C. Paz', 4 );
INSERT INTO city(description,state_id) VALUES ('Avellaneda', 12 );
INSERT INTO city(description,state_id) VALUES ('Crucecita', 12 );
INSERT INTO city(description,state_id) VALUES ('Dock Sud', 12 );
INSERT INTO city(description,state_id) VALUES ('Gerli', 12 );
INSERT INTO city(description,state_id) VALUES ('Piñeyro', 12 );
INSERT INTO city(description,state_id) VALUES ('Sarandí', 12 );
INSERT INTO city(description,state_id) VALUES ('Villa Domínico', 12 );
INSERT INTO city(description,state_id) VALUES ('Wilde', 12 );
INSERT INTO city(description,state_id) VALUES ('Berazategui', 13 );
INSERT INTO city(description,state_id) VALUES ('Hudson', 13 );
INSERT INTO city(description,state_id) VALUES ('Juan María Gutiérrez', 13 );
INSERT INTO city(description,state_id) VALUES ('Ranelagh', 13 );
INSERT INTO city(description,state_id) VALUES ('Sourigues', 13 );
INSERT INTO city(description,state_id) VALUES ('Pereyra', 13 );
INSERT INTO city(description,state_id) VALUES ('Plátanos', 13 );
INSERT INTO city(description,state_id) VALUES ('Villa España', 13 );
INSERT INTO city(description,state_id) VALUES ('Centro Agrícola El Pato', 13 );
INSERT INTO city(description,state_id) VALUES ('Nueve de Abril', 14 );
INSERT INTO city(description,state_id) VALUES ('Canning', 14 );
INSERT INTO city(description,state_id) VALUES ('El Jagüel', 14 );
INSERT INTO city(description,state_id) VALUES ('Luis Guillón', 14 );
INSERT INTO city(description,state_id) VALUES ('Monte Grande', 14 );
INSERT INTO city(description,state_id) VALUES ('Bosques', 15 );
INSERT INTO city(description,state_id) VALUES ('Estanislao Severo Zeballos', 15 );
INSERT INTO city(description,state_id) VALUES ('San Juan Bautista', 15 );
INSERT INTO city(description,state_id) VALUES ('Gobernador Julio A. Costa', 15 );
INSERT INTO city(description,state_id) VALUES ('Ingeniero Juan Allan', 15 );
INSERT INTO city(description,state_id) VALUES ('Villa Brown', 15 );
INSERT INTO city(description,state_id) VALUES ('Villa San Luis', 15 );
INSERT INTO city(description,state_id) VALUES ('Villa Santa Rosa', 15 );
INSERT INTO city(description,state_id) VALUES ('Villa Vatteone', 15 );
INSERT INTO city(description,state_id) VALUES ('La Capilla', 15 );
INSERT INTO city(description,state_id) VALUES ('Gerli', 16 );
INSERT INTO city(description,state_id) VALUES ('Lanús Este', 16 );
INSERT INTO city(description,state_id) VALUES ('Lanús Oeste', 16 );
INSERT INTO city(description,state_id) VALUES ('Monte Chingolo', 16 );
INSERT INTO city(description,state_id) VALUES ('Remedios de Escalada', 16 );
INSERT INTO city(description,state_id) VALUES ('Valentín Alsina', 16 );
INSERT INTO city(description,state_id) VALUES ('Lomas de Zamora', 17 );
INSERT INTO city(description,state_id) VALUES ('Banfield', 17 );
INSERT INTO city(description,state_id) VALUES ('Temperley', 17 );
INSERT INTO city(description,state_id) VALUES ('Llavallol', 17 );
INSERT INTO city(description,state_id) VALUES ('Turdera', 17 );
INSERT INTO city(description,state_id) VALUES ('Villa Centenario', 17 );
INSERT INTO city(description,state_id) VALUES ('Villa Fiorito', 17 );
INSERT INTO city(description,state_id) VALUES ('Ingeniero Budge', 17 );
INSERT INTO city(description,state_id) VALUES ('Villa Albertina', 17 );
INSERT INTO city(description,state_id) VALUES ('San José', 17 );
INSERT INTO city(description,state_id) VALUES ('Bernal', 18 );
INSERT INTO city(description,state_id) VALUES ('Don Bosco', 18 );
INSERT INTO city(description,state_id) VALUES ('Ezpeleta', 18 );
INSERT INTO city(description,state_id) VALUES ('Quilmes', 18 );
INSERT INTO city(description,state_id) VALUES ('San Francisco Solano', 18 );
INSERT INTO city(description,state_id) VALUES ('Villa La Florida', 18 );
INSERT INTO city(description,state_id) VALUES ('Hurlingham', 19 );
INSERT INTO city(description,state_id) VALUES ('William C. Morris', 19 );
INSERT INTO city(description,state_id) VALUES ('Villa Tesei', 19 );
INSERT INTO city(description,state_id) VALUES ('Ituzaingó', 20 );
INSERT INTO city(description,state_id) VALUES ('Villa Udaondo', 20 );
INSERT INTO city(description,state_id) VALUES ('San Justo', 21 );
INSERT INTO city(description,state_id) VALUES ('Ramos Mejía', 21 );
INSERT INTO city(description,state_id) VALUES ('Aldo Bonzi', 21 );
INSERT INTO city(description,state_id) VALUES ('Rafael Castillo', 21 );
INSERT INTO city(description,state_id) VALUES ('Ciudad Evita', 21 );
INSERT INTO city(description,state_id) VALUES ('González Catán', 21 );
INSERT INTO city(description,state_id) VALUES ('Gregorio de Laferrere', 21 );
INSERT INTO city(description,state_id) VALUES ('La Tablada', 21 );
INSERT INTO city(description,state_id) VALUES ('Lomas del Mirador', 21 );
INSERT INTO city(description,state_id) VALUES ('Isidro Casanova', 21 );
INSERT INTO city(description,state_id) VALUES ('Tapiales', 21 );
INSERT INTO city(description,state_id) VALUES ('Veinte de Junio', 21 );
INSERT INTO city(description,state_id) VALUES ('Villa Eduardo Madero', 21 );
INSERT INTO city(description,state_id) VALUES ('Villa Luzuriaga', 21 );
INSERT INTO city(description,state_id) VALUES ('Virrey del Pino', 21 );
INSERT INTO city(description,state_id) VALUES ('Merlo', 22 );
INSERT INTO city(description,state_id) VALUES ('San Antonio de Padua', 22 );
INSERT INTO city(description,state_id) VALUES ('Libertad', 22 );
INSERT INTO city(description,state_id) VALUES ('Mariano Acosta', 22 );
INSERT INTO city(description,state_id) VALUES ('Parque San Martín', 22 );
INSERT INTO city(description,state_id) VALUES ('Pontevedra', 22 );
INSERT INTO city(description,state_id) VALUES ('Moreno', 23 );
INSERT INTO city(description,state_id) VALUES ('La Reja', 23 );
INSERT INTO city(description,state_id) VALUES ('Francisco Álvarez', 23 );
INSERT INTO city(description,state_id) VALUES ('Cuartel V', 23 );
INSERT INTO city(description,state_id) VALUES ('Trujui', 23 );
INSERT INTO city(description,state_id) VALUES ('Paso del Rey', 23 );
INSERT INTO city(description,state_id) VALUES ('Morón', 24 );
INSERT INTO city(description,state_id) VALUES ('Castelar', 24 );
INSERT INTO city(description,state_id) VALUES ('Haedo', 24 );
INSERT INTO city(description,state_id) VALUES ('El Palomar', 24 );
INSERT INTO city(description,state_id) VALUES ('Villa Sarmiento', 24 );
INSERT INTO city(description,state_id) VALUES ('Caseros', 25 );
INSERT INTO city(description,state_id) VALUES ('Churruca', 25 );
INSERT INTO city(description,state_id) VALUES ('Ciudad Jardín Lomas del Palomar', 25 );
INSERT INTO city(description,state_id) VALUES ('Ciudadela', 25 );
INSERT INTO city(description,state_id) VALUES ('El Libertador', 25 );
INSERT INTO city(description,state_id) VALUES ('José Ingenieros', 25 );
INSERT INTO city(description,state_id) VALUES ('Loma Hermosa', 25 );
INSERT INTO city(description,state_id) VALUES ('Martín Coronado', 25 );
INSERT INTO city(description,state_id) VALUES ('Once de Septiembre', 25 );
INSERT INTO city(description,state_id) VALUES ('Pablo Podestá', 25 );
INSERT INTO city(description,state_id) VALUES ('Remedios de Escalada', 25 );
INSERT INTO city(description,state_id) VALUES ('Sáenz Peña', 25 );
INSERT INTO city(description,state_id) VALUES ('Santos Lugares', 25 );
INSERT INTO city(description,state_id) VALUES ('Villa Bosch', 25 );
INSERT INTO city(description,state_id) VALUES ('Villa Raffo', 25 );
INSERT INTO city(description,state_id) VALUES ('Adolfo Gonzales Chaves', 26 );
INSERT INTO city(description,state_id) VALUES ('De la Garma', 26 );
INSERT INTO city(description,state_id) VALUES ('Juan Eulogio Barra', 26 );
INSERT INTO city(description,state_id) VALUES ('Vásquez', 26 );
INSERT INTO city(description,state_id) VALUES ('Carhué', 27 );
INSERT INTO city(description,state_id) VALUES ('Rivera', 27 );
INSERT INTO city(description,state_id) VALUES ('Villa Maza', 27 );
INSERT INTO city(description,state_id) VALUES ('Espartillar', 27 );
INSERT INTO city(description,state_id) VALUES ('San Miguel Arcángel', 27 );
INSERT INTO city(description,state_id) VALUES ('Esteban Agustín Gascón', 27 );
INSERT INTO city(description,state_id) VALUES ('Delfín Huergo', 27 );
INSERT INTO city(description,state_id) VALUES ('La Pala', 27 );
INSERT INTO city(description,state_id) VALUES ('Thames', 27 );
INSERT INTO city(description,state_id) VALUES ('Yutuyaco', 27 );
INSERT INTO city(description,state_id) VALUES ('Alberti', 28 );
INSERT INTO city(description,state_id) VALUES ('Mechita', 28 );
INSERT INTO city(description,state_id) VALUES ('Villa Ortiz', 28 );
INSERT INTO city(description,state_id) VALUES ('Plá', 28 );
INSERT INTO city(description,state_id) VALUES ('Coronel Seguí', 28 );
INSERT INTO city(description,state_id) VALUES ('Villa Grisolía', 28 );
INSERT INTO city(description,state_id) VALUES ('Villa María', 28 );
INSERT INTO city(description,state_id) VALUES ('Gobernador Ugarte', 28 );
INSERT INTO city(description,state_id) VALUES ('Arrecifes', 29 );
INSERT INTO city(description,state_id) VALUES ('Todd', 29 );
INSERT INTO city(description,state_id) VALUES ('Viña', 29 );
INSERT INTO city(description,state_id) VALUES ('Ayacucho', 30 );
INSERT INTO city(description,state_id) VALUES ('Udaquiola', 30 );
INSERT INTO city(description,state_id) VALUES ('La Constancia ', 30 );
INSERT INTO city(description,state_id) VALUES ('Solanet', 30 );
INSERT INTO city(description,state_id) VALUES ('Azul', 31 );
INSERT INTO city(description,state_id) VALUES ('Chillar', 31 );
INSERT INTO city(description,state_id) VALUES ('Cacharí', 31 );
INSERT INTO city(description,state_id) VALUES ('Dieciséis de Julio', 31 );
INSERT INTO city(description,state_id) VALUES ('Ariel', 31 );
INSERT INTO city(description,state_id) VALUES ('Bahía Blanca', 32 );
INSERT INTO city(description,state_id) VALUES ('General Daniel Cerri', 32 );
INSERT INTO city(description,state_id) VALUES ('Cabildo', 32 );
INSERT INTO city(description,state_id) VALUES ('Grünbein', 32 );
INSERT INTO city(description,state_id) VALUES ('Ingeniero White', 32 );
INSERT INTO city(description,state_id) VALUES ('Villa Bordeu', 32 );
INSERT INTO city(description,state_id) VALUES ('Villa Espora', 32 );
INSERT INTO city(description,state_id) VALUES ('Villa Harding Green', 32 );
INSERT INTO city(description,state_id) VALUES ('Villa Stella Maris', 32 );
INSERT INTO city(description,state_id) VALUES ('Villa Nueva', 32 );
INSERT INTO city(description,state_id) VALUES ('Rosendo López', 32 );
INSERT INTO city(description,state_id) VALUES ('San Agustín', 33 );
INSERT INTO city(description,state_id) VALUES ('Los Pinos', 33 );
INSERT INTO city(description,state_id) VALUES ('Napaleofú', 33 );
INSERT INTO city(description,state_id) VALUES ('Balcarce', 33 );
INSERT INTO city(description,state_id) VALUES ('Ramos Otero', 33 );
INSERT INTO city(description,state_id) VALUES ('Villa Laguna La Brava', 33 );
INSERT INTO city(description,state_id) VALUES ('Baradero', 34 );
INSERT INTO city(description,state_id) VALUES ('Villa Alsina', 34 );
INSERT INTO city(description,state_id) VALUES ('Estación Ireneo Portela', 34 );
INSERT INTO city(description,state_id) VALUES ('Santa Coloma', 34 );
INSERT INTO city(description,state_id) VALUES ('Benito Juárez', 35 );
INSERT INTO city(description,state_id) VALUES ('Villa Cacique', 35 );
INSERT INTO city(description,state_id) VALUES ('Barker', 35 );
INSERT INTO city(description,state_id) VALUES ('Estación López', 35 );
INSERT INTO city(description,state_id) VALUES ('Tedín Uriburu', 35 );
INSERT INTO city(description,state_id) VALUES ('Berisso', 36 );
INSERT INTO city(description,state_id) VALUES ('Villa Porteña', 36 );
INSERT INTO city(description,state_id) VALUES ('Villa Progreso', 36 );
INSERT INTO city(description,state_id) VALUES ('Villa San Carlos', 36 );
INSERT INTO city(description,state_id) VALUES ('Barrio El Carmen Este', 36 );
INSERT INTO city(description,state_id) VALUES ('Villa Dolores', 36 );
INSERT INTO city(description,state_id) VALUES ('Villa Independencia', 36 );
INSERT INTO city(description,state_id) VALUES ('Villa Corbalan', 36 );
INSERT INTO city(description,state_id) VALUES ('Villa Argüello', 36 );
INSERT INTO city(description,state_id) VALUES ('Villa Zula', 36 );
INSERT INTO city(description,state_id) VALUES ('Barrio Banco Provincia', 36 );
INSERT INTO city(description,state_id) VALUES ('Villa Nueva', 36 );
INSERT INTO city(description,state_id) VALUES ('Barrio Universitario', 36 );
INSERT INTO city(description,state_id) VALUES ('Los Talas', 36 );
INSERT INTO city(description,state_id) VALUES ('Palo Blanco', 36 );
INSERT INTO city(description,state_id) VALUES ('Villa Banco Constructor', 36 );
INSERT INTO city(description,state_id) VALUES ('Los Catorce', 36 );
INSERT INTO city(description,state_id) VALUES ('Villa España', 36 );
INSERT INTO city(description,state_id) VALUES ('La Balandra', 36 );
INSERT INTO city(description,state_id) VALUES ('Juan B.Justo', 36 );
INSERT INTO city(description,state_id) VALUES ('Barrio Obrero', 36 );
INSERT INTO city(description,state_id) VALUES ('Barrio Santa Teresita', 36 );
INSERT INTO city(description,state_id) VALUES ('San Carlos de Bolívar', 37 );
INSERT INTO city(description,state_id) VALUES ('Urdampilleta', 37 );
INSERT INTO city(description,state_id) VALUES ('Pirovano', 37 );
INSERT INTO city(description,state_id) VALUES ('Hale', 37 );
INSERT INTO city(description,state_id) VALUES ('Juan F. Ibarra', 37 );
INSERT INTO city(description,state_id) VALUES ('Paula', 37 );
INSERT INTO city(description,state_id) VALUES ('Mariano Unzué', 37 );
INSERT INTO city(description,state_id) VALUES ('Villa Lynch Pueyrredón', 37 );
INSERT INTO city(description,state_id) VALUES ('Paraje Vallimanca', 37 );
INSERT INTO city(description,state_id) VALUES ('Paraje Villa Sanz', 37 );
INSERT INTO city(description,state_id) VALUES ('Bragado', 38 );
INSERT INTO city(description,state_id) VALUES ('General Eduardo O Brien', 38 );
INSERT INTO city(description,state_id) VALUES ('Mechita', 38 );
INSERT INTO city(description,state_id) VALUES ('Comodoro Py', 38 );
INSERT INTO city(description,state_id) VALUES ('Warnes', 38 );
INSERT INTO city(description,state_id) VALUES ('Irala', 38 );
INSERT INTO city(description,state_id) VALUES ('Olascoaga', 38 );
INSERT INTO city(description,state_id) VALUES ('Máximo Fernández', 38 );
INSERT INTO city(description,state_id) VALUES ('La Limpia', 38 );
INSERT INTO city(description,state_id) VALUES ('Asamblea', 38 );
INSERT INTO city(description,state_id) VALUES ('Brandsen', 39 );
INSERT INTO city(description,state_id) VALUES ('Jeppener', 39 );
INSERT INTO city(description,state_id) VALUES ('Altamirano', 39 );
INSERT INTO city(description,state_id) VALUES ('Gómez', 39 );
INSERT INTO city(description,state_id) VALUES ('Oliden', 39 );
INSERT INTO city(description,state_id) VALUES ('Samborombón', 39 );
INSERT INTO city(description,state_id) VALUES ('Campana', 40 );
INSERT INTO city(description,state_id) VALUES ('Alto Los Cardales', 40 );
INSERT INTO city(description,state_id) VALUES ('Lomas del Río Luján', 40 );
INSERT INTO city(description,state_id) VALUES ('Ingeniero Rómulo Otamendi', 40 );
INSERT INTO city(description,state_id) VALUES ('Cañuelas', 41 );
INSERT INTO city(description,state_id) VALUES ('Santa Rosa', 41 );
INSERT INTO city(description,state_id) VALUES ('Alejandro Petión', 41 );
INSERT INTO city(description,state_id) VALUES ('Máximo Paz', 41 );
INSERT INTO city(description,state_id) VALUES ('Uribelarrea', 41 );
INSERT INTO city(description,state_id) VALUES ('Vicente Casares', 41 );
INSERT INTO city(description,state_id) VALUES ('Gobernador Udaondo', 41 );
INSERT INTO city(description,state_id) VALUES ('El Taladro', 41 );
INSERT INTO city(description,state_id) VALUES ('Capitán Sarmiento', 42 );
INSERT INTO city(description,state_id) VALUES ('La Luisa', 42 );
INSERT INTO city(description,state_id) VALUES ('Carlos Casares', 43 );
INSERT INTO city(description,state_id) VALUES ('Smith', 43 );
INSERT INTO city(description,state_id) VALUES ('Bellocq', 43 );
INSERT INTO city(description,state_id) VALUES ('Moctezuma', 43 );
INSERT INTO city(description,state_id) VALUES ('Cadret', 43 );
INSERT INTO city(description,state_id) VALUES ('Hortensia', 43 );
INSERT INTO city(description,state_id) VALUES ('Ordoqui', 43 );
INSERT INTO city(description,state_id) VALUES ('Mauricio Hirsch', 43 );
INSERT INTO city(description,state_id) VALUES ('Colonia Mauricio', 43 );
INSERT INTO city(description,state_id) VALUES ('La Sofía', 43 );
INSERT INTO city(description,state_id) VALUES ('Carlos Tejedor', 44 );
INSERT INTO city(description,state_id) VALUES ('Tres Algarrobos', 44 );
INSERT INTO city(description,state_id) VALUES ('Colonia Seré', 44 );
INSERT INTO city(description,state_id) VALUES ('Timote', 44 );
INSERT INTO city(description,state_id) VALUES ('Curarú', 44 );
INSERT INTO city(description,state_id) VALUES ('Carmen de Areco', 45 );
INSERT INTO city(description,state_id) VALUES ('Tres Sargentos', 45 );
INSERT INTO city(description,state_id) VALUES ('Pueblo Gouin', 45 );
INSERT INTO city(description,state_id) VALUES ('Castelli', 46 );
INSERT INTO city(description,state_id) VALUES ('Centro Guerrero', 46 );
INSERT INTO city(description,state_id) VALUES ('Cerro de la Gloria', 46 );
INSERT INTO city(description,state_id) VALUES ('Chacabuco', 47 );
INSERT INTO city(description,state_id) VALUES ('Rawson', 47 );
INSERT INTO city(description,state_id) VALUES ('O Higgins', 47 );
INSERT INTO city(description,state_id) VALUES ('Castilla', 47 );
INSERT INTO city(description,state_id) VALUES ('Los Ángeles', 47 );
INSERT INTO city(description,state_id) VALUES ('Chascomús', 48 );
INSERT INTO city(description,state_id) VALUES ('Chivilcoy', 49 );
INSERT INTO city(description,state_id) VALUES ('Moquehuá', 49 );
INSERT INTO city(description,state_id) VALUES ('Gorostiaga', 49 );
INSERT INTO city(description,state_id) VALUES ('Emilio Ayarza', 49 );
INSERT INTO city(description,state_id) VALUES ('La Rica', 49 );
INSERT INTO city(description,state_id) VALUES ('San Sebastián', 49 );
INSERT INTO city(description,state_id) VALUES ('Benítez', 49 );
INSERT INTO city(description,state_id) VALUES ('Henry Bell', 49 );
INSERT INTO city(description,state_id) VALUES ('Indacochea', 49 );
INSERT INTO city(description,state_id) VALUES ('Palemon Huergo', 49 );
INSERT INTO city(description,state_id) VALUES ('Ramón Biaus', 49 );
INSERT INTO city(description,state_id) VALUES ('Colón', 50 );
INSERT INTO city(description,state_id) VALUES ('Pearson', 50 );
INSERT INTO city(description,state_id) VALUES ('Sarasa', 50 );
INSERT INTO city(description,state_id) VALUES ('El Arbolito', 50 );
INSERT INTO city(description,state_id) VALUES ('Coronel Dorrego', 51 );
INSERT INTO city(description,state_id) VALUES ('Oriente', 51 );
INSERT INTO city(description,state_id) VALUES ('El Perdido', 51 );
INSERT INTO city(description,state_id) VALUES ('Aparicio', 51 );
INSERT INTO city(description,state_id) VALUES ('San Román', 51 );
INSERT INTO city(description,state_id) VALUES ('Balneario Marisol', 51 );
INSERT INTO city(description,state_id) VALUES ('Irene', 51 );
INSERT INTO city(description,state_id) VALUES ('Faro', 51 );
INSERT INTO city(description,state_id) VALUES ('Coronel Pringles', 52 );
INSERT INTO city(description,state_id) VALUES ('Indio Rico', 52 );
INSERT INTO city(description,state_id) VALUES ('Lartigau', 52 );
INSERT INTO city(description,state_id) VALUES ('El Pensamiento', 52 );
INSERT INTO city(description,state_id) VALUES ('El Divisorio', 52 );
INSERT INTO city(description,state_id) VALUES ('Frapal', 52 );
INSERT INTO city(description,state_id) VALUES ('Punta Alta', 53 );
INSERT INTO city(description,state_id) VALUES ('Villa General Arias', 53 );
INSERT INTO city(description,state_id) VALUES ('Balneario Pehuen-Có', 53 );
INSERT INTO city(description,state_id) VALUES ('Villa del Mar', 53 );
INSERT INTO city(description,state_id) VALUES ('Bajo Hondo ', 53 );
INSERT INTO city(description,state_id) VALUES ('Puerto Rosales', 53 );
INSERT INTO city(description,state_id) VALUES ('Arroyo Pareja', 53 );
INSERT INTO city(description,state_id) VALUES ('Punta Ancla', 53 );
INSERT INTO city(description,state_id) VALUES ('Coronel Suárez', 54 );
INSERT INTO city(description,state_id) VALUES ('Huanguelén', 54 );
INSERT INTO city(description,state_id) VALUES ('San José', 54 );
INSERT INTO city(description,state_id) VALUES ('Santa María', 54 );
INSERT INTO city(description,state_id) VALUES ('Santa Trinidad', 54 );
INSERT INTO city(description,state_id) VALUES ('Villa Arcadia', 54 );
INSERT INTO city(description,state_id) VALUES ('Pasman', 54 );
INSERT INTO city(description,state_id) VALUES ('Cura Malal', 54 );
INSERT INTO city(description,state_id) VALUES ('D Orbigny', 54 );
INSERT INTO city(description,state_id) VALUES ('Cascada', 54 );
INSERT INTO city(description,state_id) VALUES ('Daireaux', 55 );
INSERT INTO city(description,state_id) VALUES ('Mouras', 55 );
INSERT INTO city(description,state_id) VALUES ('Arboledas', 55 );
INSERT INTO city(description,state_id) VALUES ('La Copeta', 55 );
INSERT INTO city(description,state_id) VALUES ('La Larga', 55 );
INSERT INTO city(description,state_id) VALUES ('Andant', 55 );
INSERT INTO city(description,state_id) VALUES ('Freyre', 55 );
INSERT INTO city(description,state_id) VALUES ('San Clemente del Tuyú', 56 );
INSERT INTO city(description,state_id) VALUES ('Las Toninas', 56 );
INSERT INTO city(description,state_id) VALUES ('Costa Chica', 56 );
INSERT INTO city(description,state_id) VALUES ('Santa Teresita', 56 );
INSERT INTO city(description,state_id) VALUES ('Mar del Tuyú', 56 );
INSERT INTO city(description,state_id) VALUES ('Costa del Este', 56 );
INSERT INTO city(description,state_id) VALUES ('Aguas Verdes', 56 );
INSERT INTO city(description,state_id) VALUES ('La Lucila del Mar', 56 );
INSERT INTO city(description,state_id) VALUES ('Costa Azul', 56 );
INSERT INTO city(description,state_id) VALUES ('San Bernardo del Tuyú', 56 );
INSERT INTO city(description,state_id) VALUES ('Mar de Ajó', 56 );
INSERT INTO city(description,state_id) VALUES ('Nueva Atlantis', 56 );
INSERT INTO city(description,state_id) VALUES ('Punta Médanos', 56 );
INSERT INTO city(description,state_id) VALUES ('Pinar del Sol', 56 );
INSERT INTO city(description,state_id) VALUES ('Costa Esmeralda', 56 );
INSERT INTO city(description,state_id) VALUES ('Dolores', 57 );
INSERT INTO city(description,state_id) VALUES ('Sevigne', 57 );
INSERT INTO city(description,state_id) VALUES ('Ensenada', 58 );
INSERT INTO city(description,state_id) VALUES ('Punta Lara', 58 );
INSERT INTO city(description,state_id) VALUES ('Villa Catella', 58 );
INSERT INTO city(description,state_id) VALUES ('Dique Nº 1', 58 );
INSERT INTO city(description,state_id) VALUES ('Isla Santiago Oeste', 58 );
INSERT INTO city(description,state_id) VALUES ('Garín', 59 );
INSERT INTO city(description,state_id) VALUES ('Belén de Escobar', 59 );
INSERT INTO city(description,state_id) VALUES ('Ingeniero Maschwitz', 59 );
INSERT INTO city(description,state_id) VALUES ('Matheu', 59 );
INSERT INTO city(description,state_id) VALUES ('Maquinista F. Savio', 59 );
INSERT INTO city(description,state_id) VALUES ('Capilla del Señor', 60 );
INSERT INTO city(description,state_id) VALUES ('Los Cardales', 60 );
INSERT INTO city(description,state_id) VALUES ('Pavón', 60 );
INSERT INTO city(description,state_id) VALUES ('Arroyo de La Cruz', 60 );
INSERT INTO city(description,state_id) VALUES ('Parada Orlando', 60 );
INSERT INTO city(description,state_id) VALUES ('Parada Robles', 60 );
INSERT INTO city(description,state_id) VALUES ('El Remanso', 60 );
INSERT INTO city(description,state_id) VALUES ('Etchegoyen', 60 );
INSERT INTO city(description,state_id) VALUES ('Parada La Lata - La Loma', 60 );
INSERT INTO city(description,state_id) VALUES ('Diego Gaynor', 60 );
INSERT INTO city(description,state_id) VALUES ('Gobernador Andonaegui', 60 );
INSERT INTO city(description,state_id) VALUES ('Chenaut', 60 );
INSERT INTO city(description,state_id) VALUES ('Ezeiza', 61 );
INSERT INTO city(description,state_id) VALUES ('Tristán Suárez', 61 );
INSERT INTO city(description,state_id) VALUES ('La Unión', 61 );
INSERT INTO city(description,state_id) VALUES ('Carlos Spegazzini', 61 );
INSERT INTO city(description,state_id) VALUES ('Aeropuerto Internacional Ezeiza', 61 );
INSERT INTO city(description,state_id) VALUES ('Canning', 61 );
INSERT INTO city(description,state_id) VALUES ('Florentino Ameghino', 62 );
INSERT INTO city(description,state_id) VALUES ('Blaquier', 62 );
INSERT INTO city(description,state_id) VALUES ('Porvenir', 62 );
INSERT INTO city(description,state_id) VALUES ('Miramar', 63 );
INSERT INTO city(description,state_id) VALUES ('Mar del Sud', 63 );
INSERT INTO city(description,state_id) VALUES ('Comandante Nicanor Otamendi', 63 );
INSERT INTO city(description,state_id) VALUES ('Mechongué', 63 );
INSERT INTO city(description,state_id) VALUES ('Centinela del Mar', 63 );
INSERT INTO city(description,state_id) VALUES ('General Alvear', 64 );
INSERT INTO city(description,state_id) VALUES ('General Arenales', 65 );
INSERT INTO city(description,state_id) VALUES ('Arribeños', 65 );
INSERT INTO city(description,state_id) VALUES ('Ascensión', 65 );
INSERT INTO city(description,state_id) VALUES ('Estación Arenales', 65 );
INSERT INTO city(description,state_id) VALUES ('Ferré', 65 );
INSERT INTO city(description,state_id) VALUES ('La Angelita', 65 );
INSERT INTO city(description,state_id) VALUES ('La Trinidad', 65 );
INSERT INTO city(description,state_id) VALUES ('General Belgrano', 66 );
INSERT INTO city(description,state_id) VALUES ('General Guido', 67 );
INSERT INTO city(description,state_id) VALUES ('Labardén', 67 );
INSERT INTO city(description,state_id) VALUES ('General La Madrid', 68 );
INSERT INTO city(description,state_id) VALUES ('La Colina', 68 );
INSERT INTO city(description,state_id) VALUES ('Líbano', 68 );
INSERT INTO city(description,state_id) VALUES ('Las Martinetas', 68 );
INSERT INTO city(description,state_id) VALUES ('Pontaut', 68 );
INSERT INTO city(description,state_id) VALUES ('Lastra', 68 );
INSERT INTO city(description,state_id) VALUES ('Quilcó', 68 );
INSERT INTO city(description,state_id) VALUES ('General Las Heras', 69 );
INSERT INTO city(description,state_id) VALUES ('Villars', 69 );
INSERT INTO city(description,state_id) VALUES ('General Hornos ', 69 );
INSERT INTO city(description,state_id) VALUES ('Plomer', 69 );
INSERT INTO city(description,state_id) VALUES ('La Choza', 69 );
INSERT INTO city(description,state_id) VALUES ('Lozano', 69 );
INSERT INTO city(description,state_id) VALUES ('Enrique Fynn', 69 );
INSERT INTO city(description,state_id) VALUES ('General Lavalle', 70 );
INSERT INTO city(description,state_id) VALUES ('Pavón', 70 );
INSERT INTO city(description,state_id) VALUES ('Chacras de San Clemente', 70 );
INSERT INTO city(description,state_id) VALUES ('General Madariaga', 71 );
INSERT INTO city(description,state_id) VALUES ('Ranchos', 72 );
INSERT INTO city(description,state_id) VALUES ('Loma Verde', 72 );
INSERT INTO city(description,state_id) VALUES ('Barrio Río Salado', 72 );
INSERT INTO city(description,state_id) VALUES ('Villanueva', 72 );
INSERT INTO city(description,state_id) VALUES ('Alegre', 72 );
INSERT INTO city(description,state_id) VALUES ('General Pinto', 73 );
INSERT INTO city(description,state_id) VALUES ('Germania', 73 );
INSERT INTO city(description,state_id) VALUES ('Villa Francia', 73 );
INSERT INTO city(description,state_id) VALUES ('Colonia San Ricardo', 73 );
INSERT INTO city(description,state_id) VALUES ('Villa Roth', 73 );
INSERT INTO city(description,state_id) VALUES ('Mar del Plata', 74 );
INSERT INTO city(description,state_id) VALUES ('Punta Mogotes', 74 );
INSERT INTO city(description,state_id) VALUES ('Las Quintas', 74 );
INSERT INTO city(description,state_id) VALUES ('Los Zorzales', 74 );
INSERT INTO city(description,state_id) VALUES ('El Sosiego', 74 );
INSERT INTO city(description,state_id) VALUES ('Estación Camet', 74 );
INSERT INTO city(description,state_id) VALUES ('Santa Angela', 74 );
INSERT INTO city(description,state_id) VALUES ('2 de Abril', 74 );
INSERT INTO city(description,state_id) VALUES ('La Adela', 74 );
INSERT INTO city(description,state_id) VALUES ('Las Margaritas', 74 );
INSERT INTO city(description,state_id) VALUES ('El Dorado', 74 );
INSERT INTO city(description,state_id) VALUES ('Colinas Verdes', 74 );
INSERT INTO city(description,state_id) VALUES ('La Gloria de la Peregrina', 74 );
INSERT INTO city(description,state_id) VALUES ('Sierra de los Padres', 74 );
INSERT INTO city(description,state_id) VALUES ('El Coyunco', 74 );
INSERT INTO city(description,state_id) VALUES ('Laguna de los Padres', 74 );
INSERT INTO city(description,state_id) VALUES ('Santa Paula', 74 );
INSERT INTO city(description,state_id) VALUES ('Batán', 74 );
INSERT INTO city(description,state_id) VALUES ('Chapadmalal', 74 );
INSERT INTO city(description,state_id) VALUES ('Felix U. Camet', 74 );
INSERT INTO city(description,state_id) VALUES ('Estación Chapadmalal', 74 );
INSERT INTO city(description,state_id) VALUES ('Los Acantilados', 74 );
INSERT INTO city(description,state_id) VALUES ('San Eduardo', 74 );
INSERT INTO city(description,state_id) VALUES ('General Rodríguez', 75 );
INSERT INTO city(description,state_id) VALUES ('Los Toldos', 76 );
INSERT INTO city(description,state_id) VALUES ('Baigorrita', 76 );
INSERT INTO city(description,state_id) VALUES ('Zavalía', 76 );
INSERT INTO city(description,state_id) VALUES ('San Emilio', 76 );
INSERT INTO city(description,state_id) VALUES ('La Delfina', 76 );
INSERT INTO city(description,state_id) VALUES ('General Villegas', 77 );
INSERT INTO city(description,state_id) VALUES ('Piedritas', 77 );
INSERT INTO city(description,state_id) VALUES ('Emilio V. Bunge', 77 );
INSERT INTO city(description,state_id) VALUES ('Coronel Charlone', 77 );
INSERT INTO city(description,state_id) VALUES ('Banderaló', 77 );
INSERT INTO city(description,state_id) VALUES ('Cañada Seca', 77 );
INSERT INTO city(description,state_id) VALUES ('Villa Sauze', 77 );
INSERT INTO city(description,state_id) VALUES ('Santa Regina', 77 );
INSERT INTO city(description,state_id) VALUES ('Villa Saboya', 77 );
INSERT INTO city(description,state_id) VALUES ('Santa Eleodora', 77 );
INSERT INTO city(description,state_id) VALUES ('Massey', 77 );
INSERT INTO city(description,state_id) VALUES ('Pichincha', 77 );
INSERT INTO city(description,state_id) VALUES ('Casbas', 78 );
INSERT INTO city(description,state_id) VALUES ('Guaminí', 78 );
INSERT INTO city(description,state_id) VALUES ('Laguna Alsina', 78 );
INSERT INTO city(description,state_id) VALUES ('Victorino de la Plaza', 78 );
INSERT INTO city(description,state_id) VALUES ('Garré', 78 );
INSERT INTO city(description,state_id) VALUES ('Arroyo Venado', 78 );
INSERT INTO city(description,state_id) VALUES ('Huanguelén', 78 );
INSERT INTO city(description,state_id) VALUES ('Henderson', 79 );
INSERT INTO city(description,state_id) VALUES ('Herrera Vegas', 79 );
INSERT INTO city(description,state_id) VALUES ('María Lucila', 79 );
INSERT INTO city(description,state_id) VALUES ('Coraceros', 79 );
INSERT INTO city(description,state_id) VALUES ('Junín', 80 );
INSERT INTO city(description,state_id) VALUES ('Morse', 80 );
INSERT INTO city(description,state_id) VALUES ('Agustín Roca', 80 );
INSERT INTO city(description,state_id) VALUES ('Fortín Tiburcio', 80 );
INSERT INTO city(description,state_id) VALUES ('Saforcada', 80 );
INSERT INTO city(description,state_id) VALUES ('Agustina', 80 );
INSERT INTO city(description,state_id) VALUES ('Laplacette', 80 );
INSERT INTO city(description,state_id) VALUES ('Balneario Laguna de Gómez', 80 );
INSERT INTO city(description,state_id) VALUES ('Abasto', 81 );
INSERT INTO city(description,state_id) VALUES ('Ángel Etcheverry', 81 );
INSERT INTO city(description,state_id) VALUES ('Arana', 81 );
INSERT INTO city(description,state_id) VALUES ('Arturo Seguí', 81 );
INSERT INTO city(description,state_id) VALUES ('Barrio El Carmen', 81 );
INSERT INTO city(description,state_id) VALUES ('Barrio Gambier', 81 );
INSERT INTO city(description,state_id) VALUES ('Barrio Las Malvinas', 81 );
INSERT INTO city(description,state_id) VALUES ('Barrio Las Quintas', 81 );
INSERT INTO city(description,state_id) VALUES ('City Bell', 81 );
INSERT INTO city(description,state_id) VALUES ('El Retiro', 81 );
INSERT INTO city(description,state_id) VALUES ('Joaquín Gorina', 81 );
INSERT INTO city(description,state_id) VALUES ('José Hernández', 81 );
INSERT INTO city(description,state_id) VALUES ('José Melchor Romero', 81 );
INSERT INTO city(description,state_id) VALUES ('La Cumbre', 81 );
INSERT INTO city(description,state_id) VALUES ('Casco Urbano', 81 );
INSERT INTO city(description,state_id) VALUES ('Lisandro Olmos', 81 );
INSERT INTO city(description,state_id) VALUES ('Los Hornos', 81 );
INSERT INTO city(description,state_id) VALUES ('Manuel B. Gonnet', 81 );
INSERT INTO city(description,state_id) VALUES ('Ringuelet', 81 );
INSERT INTO city(description,state_id) VALUES ('Altos de San Lorenzo', 81 );
INSERT INTO city(description,state_id) VALUES ('Tolosa', 81 );
INSERT INTO city(description,state_id) VALUES ('Transradio', 81 );
INSERT INTO city(description,state_id) VALUES ('Villa Elisa', 81 );
INSERT INTO city(description,state_id) VALUES ('Villa Elvira', 81 );
INSERT INTO city(description,state_id) VALUES ('Villa Garibaldi', 81 );
INSERT INTO city(description,state_id) VALUES ('Villa Montoro', 81 );
INSERT INTO city(description,state_id) VALUES ('Villa Parque Sicardi', 81 );
INSERT INTO city(description,state_id) VALUES ('Laprida', 82 );
INSERT INTO city(description,state_id) VALUES ('Pueblo San Jorge', 82 );
INSERT INTO city(description,state_id) VALUES ('Pueblo Nuevo', 82 );
INSERT INTO city(description,state_id) VALUES ('Las Flores', 83 );
INSERT INTO city(description,state_id) VALUES ('Pardo', 83 );
INSERT INTO city(description,state_id) VALUES ('El Trigo', 83 );
INSERT INTO city(description,state_id) VALUES ('Coronel Boerr', 83 );
INSERT INTO city(description,state_id) VALUES ('Vedia', 84 );
INSERT INTO city(description,state_id) VALUES ('Juan Bautista Alberdi', 84 );
INSERT INTO city(description,state_id) VALUES ('Leandro N. Alem', 84 );
INSERT INTO city(description,state_id) VALUES ('Alberdi Viejo', 84 );
INSERT INTO city(description,state_id) VALUES ('El Dorado ', 84 );
INSERT INTO city(description,state_id) VALUES ('Fortín Acha ', 84 );
INSERT INTO city(description,state_id) VALUES ('Lincoln', 85 );
INSERT INTO city(description,state_id) VALUES ('Roberts', 85 );
INSERT INTO city(description,state_id) VALUES ('Pasteur', 85 );
INSERT INTO city(description,state_id) VALUES ('El Triunfo', 85 );
INSERT INTO city(description,state_id) VALUES ('Arenaza', 85 );
INSERT INTO city(description,state_id) VALUES ('Coronel Martínez de Hoz', 85 );
INSERT INTO city(description,state_id) VALUES ('Bayauca', 85 );
INSERT INTO city(description,state_id) VALUES ('Las Toscas', 85 );
INSERT INTO city(description,state_id) VALUES ('Carlos Salas', 85 );
INSERT INTO city(description,state_id) VALUES ('Bermúdez', 85 );
INSERT INTO city(description,state_id) VALUES ('Lobería', 86 );
INSERT INTO city(description,state_id) VALUES ('San Manuel', 86 );
INSERT INTO city(description,state_id) VALUES ('Tamangueyú', 86 );
INSERT INTO city(description,state_id) VALUES ('Licenciado Matienzo', 86 );
INSERT INTO city(description,state_id) VALUES ('Pieres ', 86 );
INSERT INTO city(description,state_id) VALUES ('Arenas Verdes', 86 );
INSERT INTO city(description,state_id) VALUES ('Antonio Carboni', 87 );
INSERT INTO city(description,state_id) VALUES ('Elvira', 87 );
INSERT INTO city(description,state_id) VALUES ('José Santos Arévalo', 87 );
INSERT INTO city(description,state_id) VALUES ('Lobos', 87 );
INSERT INTO city(description,state_id) VALUES ('Empalme Lobos', 87 );
INSERT INTO city(description,state_id) VALUES ('Las Chacras', 87 );
INSERT INTO city(description,state_id) VALUES ('Salvador María', 87 );
INSERT INTO city(description,state_id) VALUES ('Zapiola', 87 );
INSERT INTO city(description,state_id) VALUES ('Carlos Keen', 88 );
INSERT INTO city(description,state_id) VALUES ('Cortines', 88 );
INSERT INTO city(description,state_id) VALUES ('José María Jáuregui', 88 );
INSERT INTO city(description,state_id) VALUES ('Luján', 88 );
INSERT INTO city(description,state_id) VALUES ('Olivera', 88 );
INSERT INTO city(description,state_id) VALUES ('Open Door', 88 );
INSERT INTO city(description,state_id) VALUES ('Torres', 88 );
INSERT INTO city(description,state_id) VALUES ('Magdalena', 89 );
INSERT INTO city(description,state_id) VALUES ('General Mansilla', 89 );
INSERT INTO city(description,state_id) VALUES ('Atalaya', 89 );
INSERT INTO city(description,state_id) VALUES ('Vieytes', 89 );
INSERT INTO city(description,state_id) VALUES ('Roberto J. Payró', 89 );
INSERT INTO city(description,state_id) VALUES ('Los Naranjos', 89 );
INSERT INTO city(description,state_id) VALUES ('Maipú', 90 );
INSERT INTO city(description,state_id) VALUES ('Las Armas', 90 );
INSERT INTO city(description,state_id) VALUES ('Santo Domingo', 90 );
INSERT INTO city(description,state_id) VALUES ('Coronel Vidal', 91 );
INSERT INTO city(description,state_id) VALUES ('General Pirán', 91 );
INSERT INTO city(description,state_id) VALUES ('La Armonía', 91 );
INSERT INTO city(description,state_id) VALUES ('Mar Chiquita', 91 );
INSERT INTO city(description,state_id) VALUES ('Mar de Cobo', 91 );
INSERT INTO city(description,state_id) VALUES ('La Baliza ', 91 );
INSERT INTO city(description,state_id) VALUES ('La Caleta', 91 );
INSERT INTO city(description,state_id) VALUES ('Mar de Cobo', 91 );
INSERT INTO city(description,state_id) VALUES ('Santa Clara del Mar', 91 );
INSERT INTO city(description,state_id) VALUES ('Atlántida', 91 );
INSERT INTO city(description,state_id) VALUES ('Camet Norte', 91 );
INSERT INTO city(description,state_id) VALUES ('Frente Mar', 91 );
INSERT INTO city(description,state_id) VALUES ('Playa Dorada', 91 );
INSERT INTO city(description,state_id) VALUES ('Santa Clara del Mar', 91 );
INSERT INTO city(description,state_id) VALUES ('Santa Elena', 91 );
INSERT INTO city(description,state_id) VALUES ('Vivoratá', 91 );
INSERT INTO city(description,state_id) VALUES ('Marcos Paz', 92 );
INSERT INTO city(description,state_id) VALUES ('Elías Romero', 92 );
INSERT INTO city(description,state_id) VALUES ('Santa Rosa', 92 );
INSERT INTO city(description,state_id) VALUES ('Lisandro de la Torre', 92 );
INSERT INTO city(description,state_id) VALUES ('Santa Marta', 92 );
INSERT INTO city(description,state_id) VALUES ('Agote', 93 );
INSERT INTO city(description,state_id) VALUES ('Gowland', 93 );
INSERT INTO city(description,state_id) VALUES ('Mercedes', 93 );
INSERT INTO city(description,state_id) VALUES ('Tomás Jofré', 93 );
INSERT INTO city(description,state_id) VALUES ('San Miguel del Monte', 94 );
INSERT INTO city(description,state_id) VALUES ('Abbott', 94 );
INSERT INTO city(description,state_id) VALUES ('Zenón Videla Dorna', 94 );
INSERT INTO city(description,state_id) VALUES ('Monte Hermoso', 95 );
INSERT INTO city(description,state_id) VALUES ('Balneario Sauce Grande', 95 );
INSERT INTO city(description,state_id) VALUES ('Navarro', 96 );
INSERT INTO city(description,state_id) VALUES ('Villa Moll', 96 );
INSERT INTO city(description,state_id) VALUES ('Las Marianas', 96 );
INSERT INTO city(description,state_id) VALUES ('José Juan Almeyra', 96 );
INSERT INTO city(description,state_id) VALUES ('Necochea', 97 );
INSERT INTO city(description,state_id) VALUES ('Quequén', 97 );
INSERT INTO city(description,state_id) VALUES ('Juan Nepomuceno Fernández', 97 );
INSERT INTO city(description,state_id) VALUES ('Nicanor Olivera', 97 );
INSERT INTO city(description,state_id) VALUES ('Claraz', 97 );
INSERT INTO city(description,state_id) VALUES ('Ramón Santamarina', 97 );
INSERT INTO city(description,state_id) VALUES ('Lumb', 97 );
INSERT INTO city(description,state_id) VALUES ('San José', 97 );
INSERT INTO city(description,state_id) VALUES ('La Negra', 97 );
INSERT INTO city(description,state_id) VALUES ('Las Grutas', 97 );
INSERT INTO city(description,state_id) VALUES ('Balneario Los Ángeles', 97 );
INSERT INTO city(description,state_id) VALUES ('Balneario Costa Bonita', 97 );
INSERT INTO city(description,state_id) VALUES ('Energía', 97 );
INSERT INTO city(description,state_id) VALUES ('Nueve de Julio', 98 );
INSERT INTO city(description,state_id) VALUES ('Dudignac', 98 );
INSERT INTO city(description,state_id) VALUES ('Alfredo Demarchi', 98 );
INSERT INTO city(description,state_id) VALUES ('Manuel B. Gonnet', 98 );
INSERT INTO city(description,state_id) VALUES ('Patricios', 98 );
INSERT INTO city(description,state_id) VALUES ('La Aurora', 98 );
INSERT INTO city(description,state_id) VALUES ('Carlos María Naón', 98 );
INSERT INTO city(description,state_id) VALUES ('Villa General Fournier', 98 );
INSERT INTO city(description,state_id) VALUES ('Morea', 98 );
INSERT INTO city(description,state_id) VALUES ('Doce de Octubre', 98 );
INSERT INTO city(description,state_id) VALUES ('Marcelino Ugarte', 98 );
INSERT INTO city(description,state_id) VALUES ('Norumbega', 98 );
INSERT INTO city(description,state_id) VALUES ('Santos Unzué', 98 );
INSERT INTO city(description,state_id) VALUES ('Sierras Bayas', 99 );
INSERT INTO city(description,state_id) VALUES ('Loma Negra', 99 );
INSERT INTO city(description,state_id) VALUES ('Sierra Chica', 99 );
INSERT INTO city(description,state_id) VALUES ('Hinojo', 99 );
INSERT INTO city(description,state_id) VALUES ('Colonia Hinojo', 99 );
INSERT INTO city(description,state_id) VALUES ('Colonia San Miguel', 99 );
INSERT INTO city(description,state_id) VALUES ('Espigas', 99 );
INSERT INTO city(description,state_id) VALUES ('Recalde', 99 );
INSERT INTO city(description,state_id) VALUES ('Villa La Serranía', 99 );
INSERT INTO city(description,state_id) VALUES ('Santa Luisa', 99 );
INSERT INTO city(description,state_id) VALUES ('Blancagrande', 99 );
INSERT INTO city(description,state_id) VALUES ('Colonia Nievas', 99 );
INSERT INTO city(description,state_id) VALUES ('Bahía San Blas', 100 );
INSERT INTO city(description,state_id) VALUES ('Cardenal Cagliero', 100 );
INSERT INTO city(description,state_id) VALUES ('Carmen de Patagones', 100 );
INSERT INTO city(description,state_id) VALUES ('José B. Casas', 100 );
INSERT INTO city(description,state_id) VALUES ('Juan A. Pradere', 100 );
INSERT INTO city(description,state_id) VALUES ('Stroeder', 100 );
INSERT INTO city(description,state_id) VALUES ('Villalonga', 100 );
INSERT INTO city(description,state_id) VALUES ('Los Pocitos', 100 );
INSERT INTO city(description,state_id) VALUES ('Villa Balnearia 7 de Marzo', 100 );
INSERT INTO city(description,state_id) VALUES ('Pehuajó', 101 );
INSERT INTO city(description,state_id) VALUES ('Juan José Paso', 101 );
INSERT INTO city(description,state_id) VALUES ('Mones Cazón', 101 );
INSERT INTO city(description,state_id) VALUES ('Francisco Madero', 101 );
INSERT INTO city(description,state_id) VALUES ('San Bernardo de Pehuajó', 101 );
INSERT INTO city(description,state_id) VALUES ('Magdala', 101 );
INSERT INTO city(description,state_id) VALUES ('Nueva Plata', 101 );
INSERT INTO city(description,state_id) VALUES ('Chiclana', 101 );
INSERT INTO city(description,state_id) VALUES ('Capitán Castro', 101 );
INSERT INTO city(description,state_id) VALUES ('Pellegrini', 102 );
INSERT INTO city(description,state_id) VALUES ('De Bary', 102 );
INSERT INTO city(description,state_id) VALUES ('Bocayuva', 102 );
INSERT INTO city(description,state_id) VALUES ('Pergamino', 103 );
INSERT INTO city(description,state_id) VALUES ('Acevedo', 103 );
INSERT INTO city(description,state_id) VALUES ('Manuel Ocampo', 103 );
INSERT INTO city(description,state_id) VALUES ('Villa Angélica', 103 );
INSERT INTO city(description,state_id) VALUES ('Juan Anchorena', 103 );
INSERT INTO city(description,state_id) VALUES ('La Violeta', 103 );
INSERT INTO city(description,state_id) VALUES ('Mariano H. Alfonzo', 103 );
INSERT INTO city(description,state_id) VALUES ('Guerrico', 103 );
INSERT INTO city(description,state_id) VALUES ('Rancagua', 103 );
INSERT INTO city(description,state_id) VALUES ('Pinzón', 103 );
INSERT INTO city(description,state_id) VALUES ('Fontezuela', 103 );
INSERT INTO city(description,state_id) VALUES ('J.A. de la Peña', 103 );
INSERT INTO city(description,state_id) VALUES ('Mariano Benítez', 103 );
INSERT INTO city(description,state_id) VALUES ('Villa San José', 103 );
INSERT INTO city(description,state_id) VALUES ('Pila', 104 );
INSERT INTO city(description,state_id) VALUES ('Casalins', 104 );
INSERT INTO city(description,state_id) VALUES ('Del Viso', 105 );
INSERT INTO city(description,state_id) VALUES ('Fátima', 105 );
INSERT INTO city(description,state_id) VALUES ('La Lonja', 105 );
INSERT INTO city(description,state_id) VALUES ('Lagomarsino', 105 );
INSERT INTO city(description,state_id) VALUES ('Manzanares', 105 );
INSERT INTO city(description,state_id) VALUES ('Pilar', 105 );
INSERT INTO city(description,state_id) VALUES ('Presidente Derqui', 105 );
INSERT INTO city(description,state_id) VALUES ('Villa Astolfi', 105 );
INSERT INTO city(description,state_id) VALUES ('Manuel Alberti', 105 );
INSERT INTO city(description,state_id) VALUES ('Villa Rosa', 105 );
INSERT INTO city(description,state_id) VALUES ('Zelaya', 105 );
INSERT INTO city(description,state_id) VALUES ('Montecarlo', 106 );
INSERT INTO city(description,state_id) VALUES ('Pinamar', 106 );
INSERT INTO city(description,state_id) VALUES ('Mar de Ostende', 106 );
INSERT INTO city(description,state_id) VALUES ('Ostende', 106 );
INSERT INTO city(description,state_id) VALUES ('Valeria del Mar', 106 );
INSERT INTO city(description,state_id) VALUES ('Cariló', 106 );
INSERT INTO city(description,state_id) VALUES ('Guernica', 107 );
INSERT INTO city(description,state_id) VALUES ('Azopardo', 108 );
INSERT INTO city(description,state_id) VALUES ('Bordenave', 108 );
INSERT INTO city(description,state_id) VALUES ('Darregueira', 108 );
INSERT INTO city(description,state_id) VALUES ('Estela', 108 );
INSERT INTO city(description,state_id) VALUES ('Felipe Solá', 108 );
INSERT INTO city(description,state_id) VALUES ('López Lecube', 108 );
INSERT INTO city(description,state_id) VALUES ('Puan', 108 );
INSERT INTO city(description,state_id) VALUES ('San Germán', 108 );
INSERT INTO city(description,state_id) VALUES ('Tres Cuervos', 108 );
INSERT INTO city(description,state_id) VALUES ('Víboras', 108 );
INSERT INTO city(description,state_id) VALUES ('Villa Castelar', 108 );
INSERT INTO city(description,state_id) VALUES ('Villa Durcudoy', 108 );
INSERT INTO city(description,state_id) VALUES ('Villa Iris', 108 );
INSERT INTO city(description,state_id) VALUES ('Verónica', 109 );
INSERT INTO city(description,state_id) VALUES ('Pipinas', 109 );
INSERT INTO city(description,state_id) VALUES ('Punta del Indio', 109 );
INSERT INTO city(description,state_id) VALUES ('Álvarez Jonte', 109 );
INSERT INTO city(description,state_id) VALUES ('Las Tahonas', 109 );
INSERT INTO city(description,state_id) VALUES ('Monte Veloz', 109 );
INSERT INTO city(description,state_id) VALUES ('Ramallo', 110 );
INSERT INTO city(description,state_id) VALUES ('El Paraíso', 110 );
INSERT INTO city(description,state_id) VALUES ('Las Bahamas', 110 );
INSERT INTO city(description,state_id) VALUES ('Pérez Millán', 110 );
INSERT INTO city(description,state_id) VALUES ('Simón Santiago Sánchez', 110 );
INSERT INTO city(description,state_id) VALUES ('Villa Ramallo', 110 );
INSERT INTO city(description,state_id) VALUES ('Villa General Savio', 110 );
INSERT INTO city(description,state_id) VALUES ('Rauch', 111 );
INSERT INTO city(description,state_id) VALUES ('Rauch', 111 );
INSERT INTO city(description,state_id) VALUES ('América', 112 );
INSERT INTO city(description,state_id) VALUES ('González Moreno', 112 );
INSERT INTO city(description,state_id) VALUES ('Fortín Olavarría', 112 );
INSERT INTO city(description,state_id) VALUES ('Sansinena', 112 );
INSERT INTO city(description,state_id) VALUES ('Roosevelt', 112 );
INSERT INTO city(description,state_id) VALUES ('Sundblad', 112 );
INSERT INTO city(description,state_id) VALUES ('Mira Pampa', 112 );
INSERT INTO city(description,state_id) VALUES ('San Mauricio', 112 );
INSERT INTO city(description,state_id) VALUES ('Rojas', 113 );
INSERT INTO city(description,state_id) VALUES ('Las Carabelas', 113 );
INSERT INTO city(description,state_id) VALUES ('Rafael Obligado', 113 );
INSERT INTO city(description,state_id) VALUES ('Los Indios', 113 );
INSERT INTO city(description,state_id) VALUES ('Villa Manuel Pomar', 113 );
INSERT INTO city(description,state_id) VALUES ('La Beba', 113 );
INSERT INTO city(description,state_id) VALUES ('Villa Parque Cecir', 113 );
INSERT INTO city(description,state_id) VALUES ('Roberto Cano', 113 );
INSERT INTO city(description,state_id) VALUES ('Sol de Mayo', 113 );
INSERT INTO city(description,state_id) VALUES ('Roque Pérez', 114 );
INSERT INTO city(description,state_id) VALUES ('Carlos Beguerie', 114 );
INSERT INTO city(description,state_id) VALUES ('Santiago Larre', 114 );
INSERT INTO city(description,state_id) VALUES ('La Reforma', 114 );
INSERT INTO city(description,state_id) VALUES ('Juan Tronconi', 114 );
INSERT INTO city(description,state_id) VALUES ('La Paz', 114 );
INSERT INTO city(description,state_id) VALUES ('La Paz chica', 114 );
INSERT INTO city(description,state_id) VALUES ('Atucha', 114 );
INSERT INTO city(description,state_id) VALUES ('Pigüé', 115 );
INSERT INTO city(description,state_id) VALUES ('Saavedra', 115 );
INSERT INTO city(description,state_id) VALUES ('Espartillar', 115 );
INSERT INTO city(description,state_id) VALUES ('Goyena', 115 );
INSERT INTO city(description,state_id) VALUES ('Arroyo Corto', 115 );
INSERT INTO city(description,state_id) VALUES ('Dufaur', 115 );
INSERT INTO city(description,state_id) VALUES ('Colonia San Martín', 115 );
INSERT INTO city(description,state_id) VALUES ('Saladillo', 116 );
INSERT INTO city(description,state_id) VALUES ('Del Carril', 116 );
INSERT INTO city(description,state_id) VALUES ('Polvaderas', 116 );
INSERT INTO city(description,state_id) VALUES ('Cazón', 116 );
INSERT INTO city(description,state_id) VALUES ('Álvarez de Toledo', 116 );
INSERT INTO city(description,state_id) VALUES ('Juan José Blaquier', 116 );
INSERT INTO city(description,state_id) VALUES ('Salliqueló', 117 );
INSERT INTO city(description,state_id) VALUES ('Quenumá', 117 );
INSERT INTO city(description,state_id) VALUES ('Salto', 118 );
INSERT INTO city(description,state_id) VALUES ('Arroyo Dulce', 118 );
INSERT INTO city(description,state_id) VALUES ('Inés Indart', 118 );
INSERT INTO city(description,state_id) VALUES ('Gahan', 118 );
INSERT INTO city(description,state_id) VALUES ('Berdier', 118 );
INSERT INTO city(description,state_id) VALUES ('La Invencible', 118 );
INSERT INTO city(description,state_id) VALUES ('San Andrés de Giles', 119 );
INSERT INTO city(description,state_id) VALUES ('Solís', 119 );
INSERT INTO city(description,state_id) VALUES ('Villa Ruiz', 119 );
INSERT INTO city(description,state_id) VALUES ('Cucullú', 119 );
INSERT INTO city(description,state_id) VALUES ('Azcuénaga', 119 );
INSERT INTO city(description,state_id) VALUES ('Villa Espil', 119 );
INSERT INTO city(description,state_id) VALUES ('Franklin', 119 );
INSERT INTO city(description,state_id) VALUES ('San Antonio de Areco', 120 );
INSERT INTO city(description,state_id) VALUES ('Villa Lía', 120 );
INSERT INTO city(description,state_id) VALUES ('Duggan', 120 );
INSERT INTO city(description,state_id) VALUES ('Vagués', 120 );
INSERT INTO city(description,state_id) VALUES ('San Cayetano', 121 );
INSERT INTO city(description,state_id) VALUES ('Ochandío', 121 );
INSERT INTO city(description,state_id) VALUES ('Balneario San Cayetano', 121 );
INSERT INTO city(description,state_id) VALUES ('Campos Salles', 122 );
INSERT INTO city(description,state_id) VALUES ('Conesa', 122 );
INSERT INTO city(description,state_id) VALUES ('Erézcano', 122 );
INSERT INTO city(description,state_id) VALUES ('General Rojo', 122 );
INSERT INTO city(description,state_id) VALUES ('La Emilia', 122 );
INSERT INTO city(description,state_id) VALUES ('San Nicolás de los Arroyos', 122 );
INSERT INTO city(description,state_id) VALUES ('Villa Campi', 122 );
INSERT INTO city(description,state_id) VALUES ('Villa Canto', 122 );
INSERT INTO city(description,state_id) VALUES ('Villa Esperanza', 122 );
INSERT INTO city(description,state_id) VALUES ('Villa Hermosa', 122 );
INSERT INTO city(description,state_id) VALUES ('Villa Riccio', 122 );
INSERT INTO city(description,state_id) VALUES ('San Pedro', 123 );
INSERT INTO city(description,state_id) VALUES ('Gobernador Castro', 123 );
INSERT INTO city(description,state_id) VALUES ('Santa Lucía', 123 );
INSERT INTO city(description,state_id) VALUES ('Río Tala', 123 );
INSERT INTO city(description,state_id) VALUES ('Pueblo Doyle', 123 );
INSERT INTO city(description,state_id) VALUES ('Obligado', 123 );
INSERT INTO city(description,state_id) VALUES ('San Vicente', 124 );
INSERT INTO city(description,state_id) VALUES ('Alejandro Korn', 124 );
INSERT INTO city(description,state_id) VALUES ('Domselaar', 124 );
INSERT INTO city(description,state_id) VALUES ('Suipacha', 125 );
INSERT INTO city(description,state_id) VALUES ('General Rivas', 125 );
INSERT INTO city(description,state_id) VALUES ('Román Báez', 125 );
INSERT INTO city(description,state_id) VALUES ('Tandil', 126 );
INSERT INTO city(description,state_id) VALUES ('María Ignacia', 126 );
INSERT INTO city(description,state_id) VALUES ('Gardey', 126 );
INSERT INTO city(description,state_id) VALUES ('De la Canal', 126 );
INSERT INTO city(description,state_id) VALUES ('Desvío Aguirre', 126 );
INSERT INTO city(description,state_id) VALUES ('Tapalqué', 127 );
INSERT INTO city(description,state_id) VALUES ('Altona', 127 );
INSERT INTO city(description,state_id) VALUES ('Crotto', 127 );
INSERT INTO city(description,state_id) VALUES ('Eufemio Uballes', 127 );
INSERT INTO city(description,state_id) VALUES ('Yerbas', 127 );
INSERT INTO city(description,state_id) VALUES ('San Bernardo', 127 );
INSERT INTO city(description,state_id) VALUES ('Covello', 127 );
INSERT INTO city(description,state_id) VALUES ('Velloso', 127 );
INSERT INTO city(description,state_id) VALUES ('La Paloma', 127 );
INSERT INTO city(description,state_id) VALUES ('General Conesa', 128 );
INSERT INTO city(description,state_id) VALUES ('Villa Roch', 128 );
INSERT INTO city(description,state_id) VALUES ('Tornquist', 129 );
INSERT INTO city(description,state_id) VALUES ('Sierra de la Ventana', 129 );
INSERT INTO city(description,state_id) VALUES ('Saldungaray', 129 );
INSERT INTO city(description,state_id) VALUES ('Villa Ventana', 129 );
INSERT INTO city(description,state_id) VALUES ('Chasicó', 129 );
INSERT INTO city(description,state_id) VALUES ('Tres Picos', 129 );
INSERT INTO city(description,state_id) VALUES ('Villa Serrana La Gruta', 129 );
INSERT INTO city(description,state_id) VALUES ('Trenque Lauquen', 130 );
INSERT INTO city(description,state_id) VALUES ('Treinta de Agosto', 130 );
INSERT INTO city(description,state_id) VALUES ('Beruti', 130 );
INSERT INTO city(description,state_id) VALUES ('Girodias', 130 );
INSERT INTO city(description,state_id) VALUES ('La Carreta', 130 );
INSERT INTO city(description,state_id) VALUES ('Tres Arroyos', 131 );
INSERT INTO city(description,state_id) VALUES ('Orense', 131 );
INSERT INTO city(description,state_id) VALUES ('Claromecó', 131 );
INSERT INTO city(description,state_id) VALUES ('Copetonas', 131 );
INSERT INTO city(description,state_id) VALUES ('Micaela Cascallares', 131 );
INSERT INTO city(description,state_id) VALUES ('San Francisco de Bellocq', 131 );
INSERT INTO city(description,state_id) VALUES ('Reta', 131 );
INSERT INTO city(description,state_id) VALUES ('Dunamar', 131 );
INSERT INTO city(description,state_id) VALUES ('San Mayol', 131 );
INSERT INTO city(description,state_id) VALUES ('Lin Calel', 131 );
INSERT INTO city(description,state_id) VALUES ('Balneario Orense', 131 );
INSERT INTO city(description,state_id) VALUES ('Barrow', 131 );
INSERT INTO city(description,state_id) VALUES ('Tres Lomas', 132 );
INSERT INTO city(description,state_id) VALUES ('Ingeniero Thompson', 132 );
INSERT INTO city(description,state_id) VALUES ('Veinticinco de Mayo', 133 );
INSERT INTO city(description,state_id) VALUES ('Norberto de La Riestra', 133 );
INSERT INTO city(description,state_id) VALUES ('Pedernales', 133 );
INSERT INTO city(description,state_id) VALUES ('Del Valle', 133 );
INSERT INTO city(description,state_id) VALUES ('Gobernador Ugarte', 133 );
INSERT INTO city(description,state_id) VALUES ('Valdés', 133 );
INSERT INTO city(description,state_id) VALUES ('San Enrique', 133 );
INSERT INTO city(description,state_id) VALUES ('Agustín Mosconi', 133 );
INSERT INTO city(description,state_id) VALUES ('Ernestina', 133 );
INSERT INTO city(description,state_id) VALUES ('Lucas Monteverde', 133 );
INSERT INTO city(description,state_id) VALUES ('Mar Azul', 134 );
INSERT INTO city(description,state_id) VALUES ('Mar de las Pampas', 134 );
INSERT INTO city(description,state_id) VALUES ('Las Gaviotas', 134 );
INSERT INTO city(description,state_id) VALUES ('Villa Gesell', 134 );
INSERT INTO city(description,state_id) VALUES ('Pedro Luro', 135 );
INSERT INTO city(description,state_id) VALUES ('Médanos', 135 );
INSERT INTO city(description,state_id) VALUES ('Mayor Buratovich', 135 );
INSERT INTO city(description,state_id) VALUES ('Hilario Ascasubi', 135 );
INSERT INTO city(description,state_id) VALUES ('Juan Cousté', 135 );
INSERT INTO city(description,state_id) VALUES ('Teniente Origone', 135 );
INSERT INTO city(description,state_id) VALUES ('Colonia San Adolfo ', 135 );
INSERT INTO city(description,state_id) VALUES ('Argerich', 135 );
INSERT INTO city(description,state_id) VALUES ('Laguna Chasicó', 135 );
INSERT INTO city(description,state_id) VALUES ('Balneario La chiquita', 135 );
INSERT INTO city(description,state_id) VALUES ('Zárate', 136 );
INSERT INTO city(description,state_id) VALUES ('Lima', 136 );
INSERT INTO city(description,state_id) VALUES ('Barrio Saavedra', 136 );
INSERT INTO city(description,state_id) VALUES ('Country Club El Casco', 136 );
INSERT INTO city(description,state_id) VALUES ('Escalada', 136 );

-- GRUPOS
INSERT INTO `group` (`name`, `text`, `description`, `create`, `delete`, `update`, `list`, `search`) 
VALUES ('Gestion de Roles', 'Roles', 'Gestion de Permisos y Accesos', 1, 1, 1, 1, 1);

INSERT INTO `group` (`name`, `text`, `description`, `create`, `delete`, `update`, `list`, `search`) 
VALUES ('Gestion de Usuarios', 'Usuarios', 'Creacion y Edicion de Usuarios Administradores', 1, 1, 1, 1, 1);

INSERT INTO `group` (`name`, `text`, `description`, `create`, `delete`, `update`, `list`, `search`) 
VALUES ('Habilitacion de Establecimiento', 'Establecimiento', 'Registro y Baja de Establecimiento', 1, 1, 0, 1, 1);

INSERT INTO `group` (`name`, `text`, `description`, `create`, `delete`, `update`, `list`, `search`)  
VALUES ('Edicion de Establecimiento', 'Mi Establecimiento', 'Edicion de informacion de Establecimiento', 0, 0, 1, 1, 1);

INSERT INTO `group` (`name`, `text`, `description`, `create`, `delete`, `update`, `list`, `search`) 
VALUES ('Gestion de Mapa de Establecimiento', 'Mapa', 'Carga y Modificacion de Mapa de Ubicaciones', 1, 1, 0, 0, 0);

INSERT INTO `group` (`name`, `text`, `description`, `create`, `delete`, `update`, `list`, `search`) 
VALUES ('Gestion de Tarifas', 'Tarifas', 'Carga y Actualizacion de Tarifas', 1, 0, 1, 1, 0);

INSERT INTO `group` (`name`, `text`, `description`, `create`, `delete`, `update`, `list`, `search`) 
VALUES ('Gestion de TIpo de Vehiculo', 'Tipo de Vehiculo', 'Creacion y Edicion de Tipos de Vehiculo', 1, 1, 1, 1, 1);

INSERT INTO `group` (`name`, `text`, `description`, `create`, `delete`, `update`, `list`, `search`) 
VALUES ('Gestion de Configuracion', 'Configuracion', 'Configuracion de la Plataforma', 1, 1, 1, 1, 1);

INSERT INTO `group` (`name`, `text`, `description`, `create`, `delete`, `update`, `list`, `search`) 
VALUES ('Acceso a Reportes', 'Reportes y Estadisticas', 'Estadisticas y Reportes del Sistema', 1, 1, 1, 1, 1);


-- ROLES ADMINISTRADOR Y CLIENTE
INSERT INTO rol (name, creationDate) VALUES ('Administrador', now());
INSERT INTO rol (name, creationDate) VALUES ('Cliente', now());

-- ROL GRUPO
INSERT INTO `permission` (`rol_id`, `group_id`) VALUES (1, 1);
INSERT INTO `permission` (`rol_id`, `group_id`) VALUES (1, 2);
INSERT INTO `permission` (`rol_id`, `group_id`) VALUES (1, 3);
INSERT INTO `permission` (`rol_id`, `group_id`) VALUES (1, 5);
INSERT INTO `permission` (`rol_id`, `group_id`) VALUES (1, 7);
INSERT INTO `permission` (`rol_id`, `group_id`) VALUES (1, 8);
INSERT INTO `permission` (`rol_id`, `group_id`) VALUES (1, 9);

INSERT INTO `permission` (`rol_id`, `group_id`) VALUES (2, 4);
INSERT INTO `permission` (`rol_id`, `group_id`) VALUES (2, 6);

-- USUARIO ADMINISTRADOR PRINCIPAL
INSERT INTO user (user,  password, name,  lastName,  email, creationDate, rol_id) 
VALUES ('ccappetto', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 'Cesar', 'Cappetto', 'cesarcappetto@gmail.com', now(), 1);

INSERT INTO user (user,  password, name,  lastName,  email, creationDate, rol_id) 
VALUES ('tlopez', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 'Tomas', 'Lopez', 'tom.lopez01@gmail.com', now(), 1);

INSERT INTO user (user,  password, name,  lastName,  email, creationDate, rol_id) 
VALUES ('flago', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 'Federico', 'Lago', 'fede333lago@gmail.com', now(), 1);

INSERT INTO user (user,  password, name,  lastName,  email, creationDate, rol_id) 
VALUES ('agariglio', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 'Alejo', 'Gariglio', 'gariglio.alejo@gmail.com', now(), 1);

INSERT INTO user (user,  password, name,  lastName,  email, creationDate, rol_id) 
VALUES ('ncarusso', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 'Nicolas', 'Carusso', 'ncarusso@gmail.com', now(), 1);

-- TIPOS DE VEHICULOS
INSERT INTO vehicle_type (name, creationDate) VALUES ('Van y Utilitarios', now()); 
INSERT INTO vehicle_type (name, creationDate) VALUES ('Pick-up y SUV', now()); 
INSERT INTO vehicle_type (name, creationDate) VALUES ('Auto', now());
INSERT INTO vehicle_type (name, creationDate) VALUES ('Motocicleta', now());

-- ESTADOS DE LAYOUT EN TIEMPO REAL
INSERT INTO layout_state (description) VALUES ('Libre');
INSERT INTO layout_state (description) VALUES ('Reservada');
INSERT INTO layout_state (description) VALUES ('Ocupada');

-- ESTADOS DE REPORTE DE BUG 
INSERT INTO bug_state (description) VALUES ('Nuevo');
INSERT INTO bug_state (description) VALUES ('Atendido');
INSERT INTO bug_state (description) VALUES ('Resuelto');